apply plugin: 'com.android.library'

android {
    compileSdkVersion 28
    buildToolsVersion '28.0.3'

    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"
        externalNativeBuild {
            ndkBuild {
                abiFilters "arm64-v8a", "x86_64"
            }
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    externalNativeBuild {
        ndkBuild {
            path file("src/main/jni/Android.mk")
        }
    }
    lintOptions {
        warning 'NewApi', 'OnClick'
        checkReleaseBuilds false
        abortOnError false
    }
}

repositories {
    maven { url 'https://jitpack.io' }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')

    api("com.github.android-hacker:exposed:master-SNAPSHOT") {
        exclude group: 'me.weishu', module: 'free_reflection'
        exclude group: 'me.weishu', module: 'epic'
    }

    implementation "com.github.tiann:FreeReflection:3.1.0"
    implementation "com.github.tiann:epic:0.11.2"
}
